// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockbatchLocalizer is an autogenerated mock type for the batchLocalizer type
type MockbatchLocalizer struct {
	mock.Mock
}

type MockbatchLocalizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockbatchLocalizer) EXPECT() *MockbatchLocalizer_Expecter {
	return &MockbatchLocalizer_Expecter{mock: &_m.Mock}
}

// ResolveLocalizedBatch provides a mock function with given fields: scientificNames
func (_m *MockbatchLocalizer) ResolveLocalizedBatch(scientificNames []string) map[string]string {
	ret := _m.Called(scientificNames)

	if len(ret) == 0 {
		panic("no return value specified for ResolveLocalizedBatch")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func([]string) map[string]string); ok {
		r0 = rf(scientificNames)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// MockbatchLocalizer_ResolveLocalizedBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveLocalizedBatch'
type MockbatchLocalizer_ResolveLocalizedBatch_Call struct {
	*mock.Call
}

// ResolveLocalizedBatch is a helper method to define mock.On call
//   - scientificNames []string
func (_e *MockbatchLocalizer_Expecter) ResolveLocalizedBatch(scientificNames interface{}) *MockbatchLocalizer_ResolveLocalizedBatch_Call {
	return &MockbatchLocalizer_ResolveLocalizedBatch_Call{Call: _e.mock.On("ResolveLocalizedBatch", scientificNames)}
}

func (_c *MockbatchLocalizer_ResolveLocalizedBatch_Call) Run(run func(scientificNames []string)) *MockbatchLocalizer_ResolveLocalizedBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockbatchLocalizer_ResolveLocalizedBatch_Call) Return(_a0 map[string]string) *MockbatchLocalizer_ResolveLocalizedBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockbatchLocalizer_ResolveLocalizedBatch_Call) RunAndReturn(run func([]string) map[string]string) *MockbatchLocalizer_ResolveLocalizedBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockbatchLocalizer creates a new instance of MockbatchLocalizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockbatchLocalizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockbatchLocalizer {
	mock := &MockbatchLocalizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
